### ISSUE TITLE
Ordering rows in a table by number actually sorts lexicographically rather than numerically.

### ISSUE THREAD

**Issue by sdall** [QuackenbushLab/grand#10]
For example, sorting the table at https://grand.networkmedicine.org/drugs/ by the number of samples results in a lexicographically ordering.

**Comment by marouenbg** [comment]
Hey @sdall ,
Thank you for reporting this, I believe it is by chance that wortmannin (997) has the largest number of samples and artemether (10) has the lowest number of samples. In the subsequent list, the lexicographic order is not maintained.

**Comment by sdall** [comment]
Hi, thanks for the quick reply!

When I sort the table by the number of samples (third column from the left), I observe cases such as 

2178 | paroxetine | 102 | 24.3398 | 331.5728 | ... | ...
-- | -- | -- | -- | -- | -- | --
2731 | trichostatin-a | 1021 | 17.7652 | 384.2524 | ... | -
3 | 10-DEBC | 105 | 35.2453 | 697.7358 | ... | -

i.e., I see 102 < 1021 < 105.

**Comment by marouenbg** [comment]
Good catch @sdall , the number were encoded as strings.

**Comment by marouenbg** [comment]
Issue fixed in https://github.com/QuackenbushLab/grand/commit/d447e33d2484fe64a9e5c7be7ae6e58c406c0bfa Thank you for spotting this @sdall !
