### ISSUE TITLE
Missing links in colon cancer drug repurposing 

### ISSUE THREAD

**Issue by Surya-Upadhyayula** [QuackenbushLab/grand#12]
Hi,

I read your paper and was trying to run one of the tutorials as mentioned in the title above. The file 'geneNames.txt' assigned to convMat variable is not traceable. Could you please provide the downloadable link for the same ? 

Thanks

**Comment by marouenbg** [comment]
Hi Surya,

Sorry for the late response, here is the file you asked for
https://netzoo.s3.us-east-2.amazonaws.com/netZooPy/tutorial_datasets/coloncancer/geneNames.txt
if you have any other questions about Netbooks, please use the issues here
https://github.com/netZoo/netbooks/issues

Thank you,
