### ISSUE TITLE
Phenotypic infromation as a file

### ISSUE THREAD

**Issue by violafanfani** [QuackenbushLab/grand#8]
Is it possible to download the phenotypic information as a file? 
Thanks

**Comment by marouenbg** [comment]
Issue solved in https://github.com/QuackenbushLab/grand/commit/0995b4fd06c96e9748ca2826eb363d40005e893c
<img width="1438" alt="Screen Shot 2022-06-23 at 11 45 58 AM" src="https://user-images.githubusercontent.com/7914548/175340763-9f31e39d-79d1-4d1c-a211-bab7a9efcf96.png">

I added a csv button to download phenotypic variables
