### ISSUE TITLE
Edge names for LIONESS COAD networks

### ISSUE THREAD

**Issue by violafanfani** [QuackenbushLab/grand#9]
I am trying to retrieve the tf-gene names for the LIONESS network file of the TCGA-COAD datasets. I am able to download the 34.1Gb file, which has size around 8millions X 445. The columns are annotated with the respective TCGA sample ID, however there is no annotation for the rows.
Is there a place where I can find the edge order?

**Comment by marouenbg** [comment]
Issue solved, I added (back) the TF and gene names the network file. The idea back then was to provide network data as they would have been generated by the corresponding implementation. In this case it was LIONESS MATLAB which does not label samples and TF/Gene Names in version 0.1. 
Thank you for the feedback !
